### ISSUE TITLE
The demo is not working: error 404.

### ISSUE THREAD

**Issue by albertinad** [vrubezhny/tern-cordovajs#5]
The demo for this plugin is not working, the server return a 404 error code (not found).

**Comment by angelozerr** [comment]
yes I had created a PR for that https://github.com/vrubezhny/tern-cordovajs/pull/3

@vrubezhny coudl you accept my PR please. Thanks!

The well url is http://demo-angelozerr.rhcloud.com/CodeMirror-Java/cordovajs.html

**Comment by albertinad** [comment]
Great! thanks for sharing! I didn't search for the new URL in PRs.
