### ISSUE TITLE
Invisibly failing for me...

### ISSUE THREAD

**Issue by davemee** [vrubezhny/tern-cordovajs#6]
I've installed tern-cordovajs and added it to the .tern-project file - I know tern is importing this plugin (sanity check: I added another plugin to the .tern-project file "PLEASE FAIL" and tern complains it cannot find it at startup) but it seems to have no impact in emacs.

I'm running spacemacs 105.4 on emacs-24.5.4 on OSX with node 4.2.2 and have confirmed tern and emacs work happily with "angular".

Any thoughts as to what may be causing this?

**Comment by angelozerr** [comment]
Which editor do you use? Which tern version do you use? What is your stack trace error? What is your .tern-project content?

**Comment by davemee** [comment]
Hi Angelo - Latest spacemacs, running on Brew Emacs. As I only installed tern yesterday (through NPM), I'm guessing it's 04-01-2016: Version 0.17

.tern-project contents are:

`{    
  "ecmaVersion": 5,    
  "libs": [    
    "browser",    
    "jquery"    
  ],    
  "plugins": {    
    "angular": {},    
    "cordovajs": {}    
  }    
}`

What throws me is that there's _no_ error, it seems to be initialising but doesn't add any of the cordova insight or completion (which I know _are_ working, as I confirmed with the angular completion).

**Comment by angelozerr** [comment]
When you are typing `cordo` and you open completion, have you a completion for `cordova`?

**Comment by davemee** [comment]
Just a '[no match]' message. No completion.

In Emacs' _messages_ buffer, this appears when I invoke completion on 'cor'

```
Undeclared variable or function 'cord'
Quit
[No matches]
```

**Comment by angelozerr** [comment]
What is your hierarchy about tern and tern-cordovajs? Have you:
- node_modules
  - tern
  - tern-cordovajs

like https://github.com/angelozerr/tern.java/tree/master/core/ternjs/node_modules

Have you a tern folder inside your tern-cordovajs/node_modules? If yes could you remove it at hand?

**Comment by davemee** [comment]
I am going to call my first child 'Angelo'. :)

My layout matched, but you're right - I had 'tern' inside tern-cordovajs/node_modules. It works beautifully now. Thank you!

**Comment by angelozerr** [comment]
> It works beautifully now. Thank you!

Cool! It's a big problem with tern when you use npm install. tern-cordovajs has depdendencies to 0.16.0 and you are using 0.17.0 When you do npm install, it installs tern 0.16.0 insode tern-cordovajs/node_modules and there are confusion like you had. I will update the package.json to avoid having your problem with 0.17.0.

I don't know cordovajs, So please create issues to improve it a lot.

For your information, it exists too https://github.com/albertinad/cordova-plugins-tern-condense which is for cordova plugin.
